## Ensure tls-secret is already applied in the namespace
---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: cert-manager-test
spec:
  ca:
    secretName: tls-secret
---

