apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticsearch.name }}
  namespace: elastic-system
spec:
  version: {{ .Chart.AppVersion }}
  nodeSets:
    - name: default
      count: {{ .Values.elasticsearch.replicas }}
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: {{ .Values.elasticsearch.storageSize }}
