{{- if .Values.agent.elasticsearch.passwordFromSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agent.elasticsearch.passwordFromSecret.name }}
  namespace: {{ .Values.agent.namespace }}
type: Opaque
stringData:
  {{ .Values.agent.elasticsearch.passwordFromSecret.key }}: {{ .Values.agent.elasticsearch.password | quote }}
{{- end }}
