{{- if .Values.kibana.enabled }}
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: {{ required "Chart.AppVersion is required" .Chart.AppVersion }}
  count: {{ .Values.kibana.replicas }}
  elasticsearchRef:
    name: {{ .Values.elasticsearch.name }}
{{- end }}
