apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: n8n
  name: n8n
  namespace: n8n
spec:
  serviceName: "n8n"
  replicas: 1
  selector:
    matchLabels:
      service: n8n
  template:
    metadata:
      labels:
        service: n8n
    spec:
      initContainers:
        - name: volume-permissions
          image: busybox:1.36
          command: ["sh", "-c", "mkdir -p /code/workflow && chown 1000:1000 /data /code/workflow"]
          volumeMounts:
            - name: n8n-claim0
              mountPath: /data
            - name: n8n-code-workflow
              mountPath: /code/workflow
      containers:
        - command:
            - /bin/sh
          args:
            - -c
            - sleep 5; n8n start
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_HOST
              value: postgres-service.n8n.svc.cluster.local
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: DB_POSTGRESDB_DATABASE
              value: n8n
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_USER
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_NON_ROOT_PASSWORD
            - name: N8N_PROTOCOL
              value: http
            - name: N8N_PORT
              value: "5678"
          image: n8nio/n8n
          name: n8n
          ports:
            - containerPort: 5678
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "500Mi"
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: n8n-claim0
            - mountPath: /code/workflow
              name: n8n-code-workflow
  volumeClaimTemplates:
    - metadata:
        name: n8n-claim0
        labels:
          service: n8n
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
    - metadata:
        name: n8n-code-workflow
        labels:
          service: n8n-code-workflow
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 250Mi
