apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-resolved.yaml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cortex
  name: cortex
spec:
  ports:
    - name: cortex-svc
      port: 9001
      targetPort: 9001
  selector:
    io.kompose.service: cortex
status:
  loadBalancer: {}
