apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: cortex
  name: cortex
spec:
  ports:
    - name: cortex-svc-9001
      port: 9001
      targetPort: 9001
  selector:
    io.kompose.service: cortex
status:
  loadBalancer: {}
