apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-resolved.yaml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: thehive
  name: thehive
spec:
  ports:
    - name: cortex-svc
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: thehive
status:
  loadBalancer: {}
