---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic
  namespace: elk
  labels:
    type: local
spec:
  storageClassName: sc-elastic
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/elastic"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-data
  namespace: elk
spec:
  storageClassName: sc-elastic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
