apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-resolved.yaml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: thehive
  name: thehive
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: thehive
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose-resolved.yaml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/hp_network: "true"
        io.kompose.service: thehive
    spec:
      containers:
        - args:
            - --no-config
            - --no-config-secret
          image: thehiveproject/thehive4:latest
          name: thehive4
          ports:
            - containerPort: 9000
          resources: {}
          volumeMounts:
            - mountPath: /etc/thehive/application.conf
              subPath: application.conf
              name: thehive-application-conf
            - mountPath: /opt/thp/thehive/db
              name: thehive-claim1
            - mountPath: /opt/thp/thehive/data
              name: thehive-claim2
            - mountPath: /opt/thp/thehive/index
              name: thehive-claim3
      restartPolicy: Always
      volumes:
        - name: thehive-application-conf
          configMap:
            name: thehive-cm
        - name: thehive-claim1
          persistentVolumeClaim:
            claimName: thehive-claim1
        - name: thehive-claim2
          persistentVolumeClaim:
            claimName: thehive-claim2
        - name: thehive-claim3
          persistentVolumeClaim:
            claimName: thehive-claim3
status: {}
