replicaCount: 2

image:
  repository: linux-endpoint-simulator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

fleet:
  # The native K8s service ECK created for Fleet Server
  url: "https://elastic-agent-agent-http.elastic-agent.svc.cluster.local:8220"
  enrollmentToken: "{{dummy-value}}"
