apiVersion: v1
name: k8s_code-server
description: A Web-IDE with ansible
version: 0.1.0
kubeVersion: ">=1.19.0"
keyword:
  - code-server
home: https://github.com/code-server
maitainers:
  - name: kindocker
