apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: n8n-code-workflow
  name: n8n-code-workflow
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
