apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: n8n
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: n8n
    spec:
      containers:
        - env:
            - name: GENERIC_TIMEZONE
              value: UTC
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_PASSWORD
              value: password
            - name: N8N_BASIC_AUTH_USER
              value: user
            - name: N8N_HOST
              value: n8n.mydev.test
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: https
            - name: N8N_SSL_KEY
              value: /root/tls.key
            - name: N8N_SSL_CERT
              value: /root/tls.crt
            - name: NODE_ENV
              value: production
            - name: WEBHOOK_URL
              value: https://n8n.mydev.test/
          image: n8nio/n8n
          name: n8n
          ports:
            - containerPort: 5678
          resources: {}
          volumeMounts:
            - mountPath: /root/.n8n
              name: n8n-claim0
            - mountPath: /root/tls.crt
              subPath: tls.crt
              name: n8n-tls-crt-vol
            - mountPath: /root/tls.key
              subPath: tls.key
              name: n8n-tls-key-vol
      restartPolicy: Always
      volumes:
        - name: n8n-claim0
          persistentVolumeClaim:
            claimName: n8n-claim0
        - name: n8n-tls-crt-vol
          configMap:
            name: n8n-tls-crt-cm
        - name: n8n-tls-key-vol
          configMap:
            name: n8n-tls-key-cm
status: {}
