apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    traefik.enable: "true"
    traefik.http.middlewares.n8n.headers.SSLHost: mydev.test
    traefik.http.middlewares.n8n.headers.SSLRedirect: "true"
    traefik.http.middlewares.n8n.headers.STSIncludeSubdomains: "true"
    traefik.http.middlewares.n8n.headers.STSPreload: "true"
    traefik.http.middlewares.n8n.headers.STSSeconds: "315360000"
    traefik.http.middlewares.n8n.headers.browserXSSFilter: "true"
    traefik.http.middlewares.n8n.headers.contentTypeNosniff: "true"
    traefik.http.middlewares.n8n.headers.forceSTSHeader: "true"
    traefik.http.routers.n8n.entrypoints: web,websecure
    traefik.http.routers.n8n.rule: Host(`n8n.mydev.test`)
    traefik.http.routers.n8n.tls: "true"
    traefik.http.routers.n8n.tls.certresolver: mytlschallenge
  creationTimestamp: null
  labels:
    io.kompose.service: n8n
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: n8n
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: n8n
    spec:
      containers:
        - env:
            - name: GENERIC_TIMEZONE
              value: UTC
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_PASSWORD
              value: password
            - name: N8N_BASIC_AUTH_USER
              value: user
            - name: N8N_HOST
              value: n8n.mydev.test
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: https
            - name: N8N_SSL_KEY
              value: /root/tls.key
            - name: N8N_SSL_CERT
              value: /root/tls.crt
            - name: NODE_ENV
              value: production
            - name: WEBHOOK_URL
              value: https://n8n.mydev.test/
          image: n8nio/n8n
          name: n8n
          ports:
            - containerPort: 5678
          resources: {}
          volumeMounts:
            - mountPath: /root/.n8n
              name: n8n-claim0
            - mountPath: /root/tls.crt
              name: n8n-tls-crt-vol
            - mountPath: /root/tls.key
              name: n8n-tls-key-vol
      restartPolicy: Always
      volumes:
        - name: n8n-claim0
          persistentVolumeClaim:
            claimName: n8n-claim0
        - name: n8n-tls-crt-vol
          configMap:
            name: n8n-tls-crt-cm
        - name: n8n-tls-key-vol
          configMap:
            name: n8n-tls-key-cm
status: {}
