apiVersion: v1
kind: Service
metadata:
  name: {{ include "splunk.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "splunk.name" . }}
    helm.sh/chart: {{ include "splunk.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: metric
      port: 8088
      targetPort: 8088
      protocol: TCP
    - name: splunk
      port: 8089
      targetPort: 8089
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "splunk.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
