---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: n8n
spec:
  type: LoadBalancer
  selector:
    app: n8n
    component: deployment
  ports:
  - protocol: TCP
    name: http
    port: 5678 
    targetPort: 5678
