apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "linux-endpoints.fullname" . }}
  labels:
    {{- include "linux-endpoints.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "linux-endpoints.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "linux-endpoints.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FLEET_URL
              value: {{ .Values.fleet.url | quote }}
            - name: ENROLLMENT_TOKEN
              value: {{ .Values.fleet.enrollmentToken | quote }}
          volumeMounts:
            # We need to mount the Elasticsearch CA cert so the agent can trust it
            - name: elasticsearch-ca
              mountPath: /etc/ssl/certs/elasticsearch-ca.crt
              subPath: ca.crt
      volumes:
        # We still need the elasticsearch CA to trust the self-signed Fleet Server!
        - name: elasticsearch-ca
          secret:
            secretName: quickstart-es-http-certs-public
