apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
spec:
  tls:
    - hosts:
      - n8n.mydev.test
      secretName: tls-secret
  rules:
  - host: n8n.mydev.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: n8n
            port:
              number: 5678

---
