apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: thehive
  name: thehive
spec:
  ports:
    - name: thehive-svc-9000
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: thehive
status:
  loadBalancer: {}
