apiVersion: v1
kind: Service
metadata:
  name: {{ include "mem0.apiServiceName" . }}
  labels:
    {{- include "mem0.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
  selector:
    {{- include "mem0.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
