{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mem0.postgresServiceName" . }}
  labels:
    {{- include "mem0.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
  selector:
    {{- include "mem0.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
