---
apiVersion: v1
kind: Service
metadata:
  name: "ldap-service"
  namespace: "ldap"
  labels:
    app.kubernetes.io/name: openldap
spec:
  ports:
    - port: 13890
  type: LoadBalancer
  selector:
    app: "openldap"
---