# elastic_basic_data.yml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elk
spec:
  version: 9.0.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          volumeMounts:
          - name: elastic-data
            mountPath: /usr/share/elasticsearch/data
        volumes:
        - name: elastic-data
          hostPath:
            path: /tmp/elastic/data
            type: DirectoryOrCreate
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elk
spec:
  version: 9.0.1
  count: 1
  elasticsearchRef:
    name: quickstart
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: quickstart-fleet-server
  namespace: elk
spec:
  version: 9.0.1
  kibanaRef:
    name: quickstart
  elasticsearchRefs:
  - name: quickstart
  mode: fleet
  fleetServerEnabled: true
  policyID: default-fleet-policy
  deployment:
    replicas: 1