apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: elk
spec:
  version: ${ELK_VERSION}
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elk
spec:
  version: ${ELK_VERSION}
  count: 1
  elasticsearchRef:
    name: quickstart
---
apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: quickstart-fleet-server
  namespace: elk
spec:
  version: ${ELK_VERSION}
  kibanaRef:
    name: quickstart
  elasticsearchRefs:
  - name: quickstart
  mode: fleet
  fleetServerEnabled: true
  policyID: default-fleet-policy  # Update with actual policy ID after Step 4
  deployment:
    replicas: 1
    podTemplate:
      spec:
        containers:
        - name: agent
          resources:
            requests:
              memory: 512Mi
              cpu: 0.2
            limits:
              memory: 1Gi
              cpu: 0.5