apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: quickstart-filebeat
  namespace: elk
spec:
  type: filebeat
  version: ${ELK_VERSION}
  config:
    filebeat.inputs:
    - type: container
      paths:
      - /var/log/containers/*.log
    processors:
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
        matchers:
        - logs_path:
            logs_path: "/var/log/containers/"
    output.file:
      path: "/tmp/filebeat"
      filename: data.log
      rotate_every_kb: 10000
      number_of_files: 7
  deployment:
    replicas: 1
    podTemplate:
      spec:
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
          resources:
            requests:
              memory: 200Mi
              cpu: 0.1
            limits:
              memory: 500Mi
              cpu: 0.5
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: filebeat-output
            mountPath: /tmp/filebeat
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: filebeat-output
          hostPath:
            path: /tmp/filebeat
            type: DirectoryOrCreate