---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic
  namespace: elk
  labels:
    type: local
spec:
  storageClassName: sc-elastic
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/elastic"
---
