apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: quickstart-filebeat
  namespace: elk
spec:
  type: filebeat
  version: ${ELK_VERSION}
  config:
    # Add debug logging
    logging.level: debug
    
    filebeat.inputs:
    - type: httpjson
      interval: 30s  # Shorter interval for faster testing
      request.url: https://api.sunrise-sunset.org/json?lat=36.7201600&lng=-4.4203400&date=2025-05-07
      request.method: GET
      # Enable request tracing for debugging
      enable_request_tracer: true
      # Simpler response decoding
      response.decode_json_fields:
        fields: ["results"]
        target: ""
        overwrite_keys: true
      processors:
      - add_fields:
          target: ''
          fields:
            source_type: sunrise_sunset_api
    
    # Simplify processors for debugging
    processors:
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
        matchers:
        - logs_path:
            logs_path: "/var/log/containers/"
    
    # Add file permissions explicitly
    output.file:
      path: "/tmp/filebeat"
      filename: data.log
      rotate_every_kb: 10000
      number_of_files: 7
      permissions: 0644  # Explicit permissions
  
  deployment:
    replicas: 1
    podTemplate:
      metadata:
        labels:
          beat-name: quickstart-filebeat
        name: quickstart-filebeat-beat
      spec:
        hostname: quickstart-filebeat-beat
        containers:
        - name: filebeat
          securityContext:
            runAsUser: 0
          resources:
            requests:
              memory: 200Mi
              cpu: 0.1
            limits:
              memory: 500Mi
              cpu: 0.5
          volumeMounts:
          - name: filebeat-output
            mountPath: /tmp/filebeat
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumes:
        - name: filebeat-output
          hostPath:
            path: /tmp/filebeat
            type: DirectoryOrCreate