apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-elastic
  labels:
    type: local
spec:
  storageClassName: sc-elastic
  capacity:
    storage: 2Gi  # Match the 2Gi requested in volumeClaimTemplates
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/elastic"