apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server-{{ .Values.user }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: code-server-{{ .Values.user }}
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server-{{ .Values.user }}
    spec:
      serviceAccountName: code-server-{{ .Values.user }}
      automountServiceAccountToken: true
      containers:
      - name: code-server
        image: gashirar/code-server-on-k8s:latest
        ports:
        - containerPort: 8080
          name: code-server
        securityContext:
          privileged: true
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: code-server-{{ .Values.user }}
              key: password
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi
