kind: Service
apiVersion: v1
metadata:
  name: code-server-{{ .Values.user }}
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: code-server-{{ .Values.user }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: code-server
    name: code-server-{{ .Values.user }}

