apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server-{{ .Values.user }}
  namespace:  {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/websocket-services: code-server-{{ .Values.user }}
spec:
  tls:
  - hosts:
    - {{ .Values.host_domain }}
    secretName: code-server-secret-{{ .Values.user }}
  rules:
  - host: {{ .Values.host_domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: code-server-{{ .Values.user }}
            port:
              number: {{ .Values.port }}
