apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: n8n-claim1
  name: n8n-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
status: {}
