apiVersion: v1
kind: Service
metadata:
  name: http-svc1
  labels:
    app: http-svc1
spec:
  ports:
  - port: 8000
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: http-svc1
  #type: LoadBalancer
---
